---
title: "Build Data Set"
author: "Dean Calahan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

# FZJ ATS Pilot 2018-2019  

## Knitting *BuildDataSet.Rmd* creates this document and builds the data set from the raw data files. Raw data is stored in *Research/Data/* and was copied there from orginal sources on FZJ servers.  

## Knitr Settings
```{r setup}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../../")
```

## Project Settings
```{r proj_settings, include=TRUE}
source("Code/R/Settings.R")
```

## Data integrity
```{r copy_files, include = TRUE}
# If Data/ exists, assume it is valid, else copy the original data from Research/Data/
CheckData()
```

## Load data from relevant Excel spreadsheets
```{r load_data, include = TRUE}
# Water chemistry and biomass productivity
treatment_2018 <- WaterChemistryBiomass2018(file.path(data_dir, "2018", "Treatment.xlsx"))
treatment_2019 <- WaterChemistryBiomass2019(file.path(data_dir, "2019", "Treatment.xlsx"))

# Biomass Elemental composition. In 2018 it was all in one spreadsheet, for 2019 it was in two
biomass_2018 <- BiomassCompositionData2018(file.path(data_dir, "2018", "Elemental Analysis.xlsx"))
biomass_2019 <- BiomassCompositionData2019(file.path(data_dir, "2019", "ICPOES.xlsx"),
                                           file.path(data_dir, "2019", "EA.xls"))

# HOBO data

# Irradiance data

```

