<!-- Copyright 2019 by Forschungszentrum-Jülich (FZ-J). -->
<!-- This file is part of the publication "FZ-J Pilot ATS Floways" -->
<!-- (FZJPAF), documenting a concept for establishing a major ATS research -->
<!-- program at Forschungszentrum Jülich. The software component of FZJPAF is -->
<!-- open access: you can redistribute it and/or modify it under the terms of the -->
<!-- GNU General Public License as published by the Free Software Foundation, -->
<!-- either version 3 of the License, or (at your option) any later version. The -->
<!-- software component of FZJPAF is distributed in the hope that it will be -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General -->
<!-- Public License for more details. You should have received a copy of the GNU -->
<!-- General Public License along with the software component of FZJPAF. If not, -->
<!-- see <http://www.gnu.org/licenses/>. -->
# Exploratory Floways
The Original Pilot ran at the final treatment tanks of the campus WWTP from August through November of 2018. It was then operated in the Novagreen greenhouse at the Algae Park until June of 2019, at which point it was moved back to the WWTP location. The floway length was extended in August of 2019, and the floway itself was divided into two narrower channels in order to perform controlled experiments, with one channel serving as a control and the other to test a treatment. This reconfiguration is not yet complete. The original floway should be replaced by two floways, perhaps of the narrow design due to limited space, each with independent plumbing. The current implementation is the result of modifications in place and doesn't reflect a standard configuration. Specifically The headworks is of a different geometry than the additional floway modules, and to produce two channels, the existing 0.5 m floway is divided in two.

This site will henceforth be called the "Exploratory Floways" to indicate its intended use to perform quick tests of operational ideas to determine whether they are worth controlled experiments at the Wastewater Floways and to work out bugs in hardware or procedures before implementing the experiment there.

## CO${_2}$ Experiments
The initial use of the Exploratory Floway will be to perform an experiment involving CO${_2}$ addition to one of the two channels. The additional required construction steps to accomplish this reconfiguration are:

* Submit a Risk Assessment covering provision the CO${_2}$ tank at the site.
* Reconfigure the site to allow safe storage and utilization of the CO${_2}$ tank.
* Assemble a gas sparging apparatus, with pH-controlled CO${_2}$ addition into one channel.
* Replace the existing dump bucket with a two-channel dump bucket.

## Obtaining Publishable Data from the Exploratory Floways
Preliminary data from the 2018 outdoors run indicate that high-phosphate biomass can be produced while substantially reducing TN and soluble P concentrations. These results suggest that a high quality algal fertilizer can be produced and that by supplementing the influent with CO${_2}$ improved productivity and N removal can be accomplished. Key studies that must be performed to complete this work are:

* Identify the chemical form and localization of P in the biomass.
* Demonstrate equivalent performance in each channel when no CO${_2}$ is added.
* Demonstrate increased biomass productivity and nutrient removal when CO${_2}$ is added.
* Demonstrate the utility of ATS biomass as a fertilizer.

This would be a relatively small paper,-preliminary results but building on previous papers. It could serve as a template for a more comprehensive paper that would incorporate results from a full year's production of algal biomass using the WWTP Floways.

As of this writing, the year is waning, and it is not certain that the floway can be kept running throughout the winter, although it is worth trying - algal growth does not stop, but rather declines, and it is worth establishing a lower limit on productivity and water treatment performance. In any case, the floway should be kept operating as long as possible. At worst, the CO${_2}$ experiments should be attempted if only to work out any bugs in the procedures. If there must be a pause in floway operations for winter, they should nevertheless be restarted as early as possible in 2020 and the CO${_2}$ experiments completed then.