---
title: 'FZ-J WWTP ATS Pilot'
subtitle: 'Data Cleaning'
author:
- Dean Calahan^[Smithsonian Institution]
- Isabel Meuser^[Forschungszentrum Jülich]
- Ladislav Nedbal^[Forschungszentrum Jülich]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, fig.height=3)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```
```{r initialize}
library(readr)
library(readxl)
library(dplyr)
library(lubridate)
library(knitr)
source("Code/R/Settings.R")
source("Code/R/FZJWWTPP.R")
```

### Temperature and Illumination, Week 1 (ATS_1)  
```{r week1}
ti_df <- CleanHOBOData(HOBO_fn[1], 1010, 365, w=1)
```

### Temperature and Illumination, Week 2 (ATS_2)  
```{r week2}
ti_df <- ti_df %>% rbind(CleanHOBOData(HOBO_fn[2], 9773, 271, w=2))
```

### Temperature and Illumination, Week 3 (ATS_1)  
```{r week3}
ti_df <- ti_df %>% rbind(CleanHOBOData(HOBO_fn[3], 119, 96, w=3))
```

### Temperature and Illumination, Week 4 (ATS_2)  
```{r week4}
ti_df <- ti_df %>% rbind(CleanHOBOData(HOBO_fn[4], 107, 227, w=4))
```

### Temperature and Illumination, Week 5 (ATS_1)  
```{r week5}
ti_df <- ti_df %>% rbind(CleanHOBOData(HOBO_fn[5], 107, 227, w=5))
```

### Temperature and Illumination, Week 6 (ATS_2)  
```{r week6}
ti_df <- ti_df %>% rbind(CleanHOBOData(HOBO_fn[6], 121, 65, w=6))
```

### Temperature and Illumination, Week 7 (ATS_1)  
```{r week7}
ti_df <- ti_df %>% rbind(CleanHOBOData(HOBO_fn[7], 84, 54, w=7))
```
```{r save_ti}
write_csv(ti_df, ti_fn)
```

# Floway Chemistry & Biomass
```{r Floway}
wc_df <- read_excel(ss_fn,
                    sheet="Tabelle1",
                    skip=3,
                    col_names=c("date",
                               "time",
                               "beforeafter",
                               "PO4dil",
                               "PO4P",
                               "PO4Pxdil",
                               "PO4Pred",
                               "dilTN",
                               "TNxdil",
                               "TN",
                               "TNred",
                               "comment",
                               "remark",
                               "assaydate",
                               "bmwet",
                               "bmdry",
                               "bmdrypct",
                               "pH"))

# Impute missing times. We take the minimum time, and simply add 24 hours to it
no_times <- which(is.na(wc_df$time))
min_time <- min(ti_df[ti_df$week == 1,]$datetime)
wc_df[which(is.na(wc_df$time)),]$time <- make_datetime(2018,
                                                       12,
                                                       31,
                                                       8,
                                                       0,
                                                       0)

# Create a new data frame with date and time combined into datetime for each observation
fw_df <- data.frame(datetime=make_datetime(year(wc_df$date),
                                           month(wc_df$date),
                                           day(wc_df$date),
                                           hour(wc_df$time),
                                           minute(wc_df$time),
                                           second(wc_df$time),
                                           tz="Europe/Berlin"))

# Make before/after a logical
fw_df$before <- TRUE
fw_df[which(wc_df$beforeafter != "before"),]$before <- FALSE

# Nutrient concentrations & pH
fw_df$PO4P <- wc_df$PO4Pxdil
fw_df$TN <- wc_df$TN
fw_df$pH <- wc_df$pH

# Make frozen/not frozen a logical
fw_df$frozen <- TRUE
fw_df[which(wc_df$comment != "frozen"),]$frozen <- FALSE

# Date of assay
fw_df$assaydate <- make_date(year(wc_df$assaydate),
                                 month(wc_df$assaydate),
                                 day(wc_df$assaydate))

# Biomass measurements
fw_df$wet_biomass <- wc_df$bmwet
fw_df$dry_biomass <- wc_df$bmdry
fw_df$solids <- wc_df$bmdrypct

# Need observation date separate from datetime to make life easier
fw_df$obsdate <- make_date(year(fw_df$datetime), month(fw_df$datetime), day(fw_df$datetime))

```
```{r save_cb}
write_csv(fw_df, cb_fn)
```
