<!-- Copyright 2019 by Forschungszentrum-Jülich (FZ-J). -->
<!-- This file is part of the publication "FZ-J Pilot ATS Floways" -->
<!-- (FZJPAF), documenting a concept for establishing a major ATS research -->
<!-- program at Forschungszentrum Jülich. The software component of FZJPAF is -->
<!-- open access: you can redistribute it and/or modify it under the terms of the -->
<!-- GNU General Public License as published by the Free Software Foundation, -->
<!-- either version 3 of the License, or (at your option) any later version. The -->
<!-- software component of FZJPAF is distributed in the hope that it will be -->
<!-- useful, but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General -->
<!-- Public License for more details. You should have received a copy of the GNU -->
<!-- General Public License along with the software component of FZJPAF. If not, -->
<!-- see <http://www.gnu.org/licenses/>. -->

\tableofcontents
\newpage
\pagenumbering{arabic}  

```{r i_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "../../")
```
```{r i_settings, include=FALSE}
source("Code/R/Settings.R")
```
# Introduction
This document describes in detail the work needed to complete reconfiguration of the small ATS pilot floway at the FZ-J campus WWTP and outlines additional work needed to complete the Exploratory Floways at the stabilization ponds and to assemble floways in the Algae Park greenhouses.
